### ISSUE TITLE
Missing tan in transform

### ISSUE THREAD

**Issue by stone-zeng** [mekkablue/VerticalSkew#3]
https://github.com/mekkablue/VerticalSkew/blob/2af9152f4ec2541d5483e0ae4c603e7ec1d15758/VerticalSkew.glyphsPalette/Contents/Resources/plugin.py#L52-L55

If `skew` is the angle, then there should be a `math.tan` at line 54, i.e.

```py
 def transform( self, skew=0.0, origin=NSZeroPoint ): 
 	myTransform = NSAffineTransform.transform() 
	myTransform.shearYBy_atCenter_(math.tan(math.radians(skew)), -origin.x)
 	return myTransform
```

**Comment by mekkablue** [comment]
Thanks, ooops! Nobody noticed, because for small angles, the tan tarnsformation makes almost no difference.
